name: Build and Upload macOS App

on:
  push:
jobs:
  build:
    runs-on: macos-latest  # Use the latest macOS runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build macOS App
        run: |
            Scheme="Health"
            XCProject="Health.xcodeproj"
            xcodebuild -jobs $(sysctl -n hw.ncpu) -project "$XCProject" -scheme "$Scheme" -configuration Release -arch arm64 -sdk osx -derivedDataPath "$TMPDIR/App" CODE_SIGNING_ALLOWED=NO DSTROOT=$AppTMP/install ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO
            mv "$(echo $TMPDIR/App/Build/Products/Release-*/*.app)" ./
            ls
      - name: Upload macOS App
        uses: actions/upload-artifact@v2
        with:
          name: App
          path: "*.app"
